package eu.fbk.st;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URL;

public class Notice {
    private JLabel lblNoticeImage;
    private JLabel lblNoticeMessage;
    private JPanel rootPanel;
    private InputStream mImage;
    private String mMessage;

    public Notice(InputStream img, String msg) {
        mImage = img;
        mMessage = msg;

        BufferedImage image = null;
        try {
            image = ImageIO.read(mImage);
        } catch (IOException e) {
            e.printStackTrace();
        }

        Image dimg = image.getScaledInstance(30, 30,
                Image.SCALE_SMOOTH);

        ImageIcon icon = new ImageIcon(dimg);
        lblNoticeImage.setIcon(icon);
        lblNoticeImage.setText("");

        lblNoticeMessage.setText(mMessage);
    }


    public JComponent getRootPanel() {
        return rootPanel;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        lblNoticeImage = new JLabel();
        lblNoticeImage.setText("");
        rootPanel.add(lblNoticeImage, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(40, 40), null, 0, false));
        lblNoticeMessage = new JLabel();
        lblNoticeMessage.setText("");
        lblNoticeMessage.putClientProperty("html.disable", Boolean.FALSE);
        rootPanel.add(lblNoticeMessage, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
